In [1]:
import numpy as np

In [2]:
array2d = np.array([[1, 2, 4], [2, 4, 8], [3, 6, 18], [4, 16, 32]])
array3d = np.array([[[.1, .4], [.2, .5], [.3, .6]], [[.7, 1.], [.8, 1.1], [.9, 1.2]]])

In [3]:
array2d = np.array([[1, 2, 4], [2, 4, 8], [3, 6, 18], [4, 16, 32]])
array3d = np.array([[[.1, .4], [.2, .5], [.3, .6]], [[.7, 1.], [.8, 1.1], [.9, 1.2]]])

print(array2d)
print(array3d)

[[ 1  2  4]
 [ 2  4  8]
 [ 3  6 18]
 [ 4 16 32]]
[[[0.1 0.4]
  [0.2 0.5]
  [0.3 0.6]]

 [[0.7 1. ]
  [0.8 1.1]
  [0.9 1.2]]]


In [4]:
print("Old Shape:", array2d.shape)
print(array2d)
array2d_new = np.reshape(array2d, (2, 6))
print("new shape:", array2d_new.shape)
print(array2d_new)

Old Shape: (4, 3)
[[ 1  2  4]
 [ 2  4  8]
 [ 3  6 18]
 [ 4 16 32]]
new shape: (2, 6)
[[ 1  2  4  2  4  8]
 [ 3  6 18  4 16 32]]


In [5]:
print("old shape:", array3d.shape)
print(array3d)
array3d_new = np.reshape(array3d, (4, 3))
print("new shape:", array3d_new.shape)
print(array3d_new)

old shape: (2, 3, 2)
[[[0.1 0.4]
  [0.2 0.5]
  [0.3 0.6]]

 [[0.7 1. ]
  [0.8 1.1]
  [0.9 1.2]]]
new shape: (4, 3)
[[0.1 0.4 0.2]
 [0.5 0.3 0.6]
 [0.7 1.  0.8]
 [1.1 0.9 1.2]]


In [6]:
array3d.reshape((4, 3))

array([[0.1, 0.4, 0.2],
       [0.5, 0.3, 0.6],
       [0.7, 1. , 0.8],
       [1.1, 0.9, 1.2]])

In [7]:
#numpy_transpose #untuk mengubah ukuran reshape

np.transpose(array2d)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6, 16],
       [ 4,  8, 18, 32]])

In [8]:
np.transpose(array2d, axes=(1, 0))

array([[ 1,  2,  3,  4],
       [ 2,  4,  6, 16],
       [ 4,  8, 18, 32]])

In [11]:
ax0, ax1, ax2 = array3d.shape
print(ax0, ax1, ax2)

2 3 2


In [9]:
np.transpose(array3d)

array([[[0.1, 0.7],
        [0.2, 0.8],
        [0.3, 0.9]],

       [[0.4, 1. ],
        [0.5, 1.1],
        [0.6, 1.2]]])

In [10]:
np.transpose(array3d, axes=(0, 2, 1))

array([[[0.1, 0.2, 0.3],
        [0.4, 0.5, 0.6]],

       [[0.7, 0.8, 0.9],
        [1. , 1.1, 1.2]]])

In [12]:
#Numpy.squeeze

rng = np.random.default_rng(11)

array_131 = rng.integers(10, size=(1, 3, 1))
array_212 = np.array([[[1, 2]], [[1, 2]]])
array_11 = np.array([[10]])
print(array_131, array_131.shape)
print(array_11, array_11.shape)
print(array_212, array_212.shape)

[[[1]
  [1]
  [7]]] (1, 3, 1)
[[10]] (1, 1)
[[[1 2]]

 [[1 2]]] (2, 1, 2)


In [ ]:
array_3 =