In [1]:
#Intro to Numpy: Numerical Python

In [2]:
import numpy as np
print(np.__version__)

1.21.2


In [5]:
list_of_list = [[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]]
print(list_of_list)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [8]:
list_of_list * 2

[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [10]:
matrix_x_scalar = []
for row in list_of_list:
    temp = []
    for item in row:
        temp.append(2 * item)
    matrix_x_scalar.append(temp)

print(matrix_x_scalar)

[[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24]]


In [ ]:
#np.array([1, 2, 3])

In [12]:
int_array = np.array([1, 2, 3])
float_array = np.array([.1, .2, .3, .4])

print(int_array, type(int_array), int_array.dtype)
print(float_array, type(int_array), float_array.dtype)

[1 2 3] <class 'numpy.ndarray'> int32
[0.1 0.2 0.3 0.4] <class 'numpy.ndarray'> float64


In [13]:
print(np.array([.1, .2, .4], dtype="int"))
print(np.array([1, 3, 4], dtype="float"))

[0 0 0]
[1. 3. 4.]


In [14]:
print(int_array.ndim, float_array.ndim)
print(int_array.shape, float_array.shape)
print(int_array.size, float_array.size)

1 1
(3,) (4,)
3 4


In [15]:
array_2x2 = np.array([[1, 2], [3, 4]])
array_1x2 = np.array([[5, 5]])
array_2x1 = np.array([[2], [4]])

print(array_2x2)
print(array_1x2)
print(array_2x1)

[[1 2]
 [3 4]]
[[5 5]]
[[2]
 [4]]


In [16]:
print([[1, 2], [3, 4]])

[[1, 2], [3, 4]]


In [17]:
print(array_2x2.ndim, array_1x2.ndim, array_2x1.ndim)
print(array_2x2.shape, array_1x2.shape, array_2x1.shape)
print(array_2x2.size, array_1x2.size, array_2x1.size)

2 2 2
(2, 2) (1, 2) (2, 1)
4 2 2


In [19]:
#No longer recommeded
m_2x2 = np.matrix ([[1, 2], [3, 4]])
print(m_2x2, type(m_2x2))

[[1 2]
 [3 4]] <class 'numpy.matrix'>


In [ ]:
#Discourage
np.array ([[1, 2], [3]])

In [20]:
#Array N-Dimensi

array_3d = np.array([[[1, 2, 1], [3, 4, 3]], [[5, 4, 5], [6, 5, 6]]])
array_4d = np.array([[[[1, 2, 1], [3, 4, 3]], [[5, 6, 5], [7, 8, 7]]], [[[12, 13, 12], [11, 12, 11]], [[13, 14, 13], [15, 16, 15]]]])

print(array_3d)
print(array_4d)

[[[1 2 1]
  [3 4 3]]

 [[5 4 5]
  [6 5 6]]]
[[[[ 1  2  1]
   [ 3  4  3]]

  [[ 5  6  5]
   [ 7  8  7]]]


 [[[12 13 12]
   [11 12 11]]

  [[13 14 13]
   [15 16 15]]]]


In [ ]:
#Quiz 2 Cek on Deepnote

In [22]:
#Penciptaan Array

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# providing dtype

np.arange(1, 10, dtype=float)
np.arange(0, 11, 2)
np.array(list(range(0, 11, 2)))
np.arange(10, 0, -1)
np.arange(1, 10. -1)
list(range(1, 10, -1))

[]

In [27]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [30]:
np.linspace(1, 10, 20, endpoint=False)

array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55])

In [29]:
np.linspace(0, 100, 50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [ ]:
# numpy.eye

In [31]:
print(np.eye(5))
print(np.eye(4, 6))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [32]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
print(np.zeros((2, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [35]:
print(np.zeros((3, 2, 4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [36]:
#Press Shift+Tab in () to see documentation

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
print(np.ones((2, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [40]:
print(np.ones((3, 2, 4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [41]:
#numpy.random

rng = np.random.default_rng()

print(rng, type(rng))


Generator(PCG64) <class 'numpy.random._generator.Generator'>


In [42]:
print(rng.standard_normal(size=5))

[ 0.66808053  0.13881723 -0.49269074  2.31192599  1.72353705]


In [43]:
print(rng.standard_normal(size=(3, 3)))

[[ 0.97094908 -0.72284951 -0.00794131]
 [-0.28328978 -0.01920112  1.69020125]
 [-0.04728731  0.58865221  1.37955004]]


In [44]:
print(rng.integers(5, 10, size=10))

[8 9 7 9 6 8 5 7 7 9]


In [45]:
print(rng.uniform(size=(2, 5)))

[[0.60636124 0.85181627 0.80452031 0.69485838 0.64531713]
 [0.60648302 0.54843039 0.71159022 0.27309541 0.43810825]]


In [46]:
print(rng.uniform(10, size=(1, 6)))

ValueError: high - low < 0

In [47]:
#default_rng

rng_with_seed = np.random.default_rng(111)

print(rng_with_seed, type(rng_with_seed))

Generator(PCG64) <class 'numpy.random._generator.Generator'>


In [48]:
print(rng.integers(5, 10, size=10))

[8 9 9 5 9 7 5 6 6 8]


In [55]:
rng_with_seed = np.random.default_rng(11)
print(rng_with_seed.integers(5, 10, size=10))

[5 5 8 7 7 8 8 5 7 5]


In [54]:
rng_with_seed = np.random.default_rng(1)
print(rng_with_seed.integers(5, 10, size=(5, 10)))

[[7 7 8 9 5 5 9 9 6 6]
 [9 7 6 9 6 7 8 7 5 5]
 [9 8 9 7 9 6 7 8 5 6]
 [5 7 9 5 6 7 9 6 7 6]
 [5 8 5 6 7 7 5 9 8 9]]


In [51]:
#Indexing, Slicing, dan Perulangan

print("array:", int_array)
print(int_array[2])
print(int_array[-2])
print(int_array[:2])

array: [1 2 3]
3
2
[1 2]


In [52]:
print("array 2D:", array_2x2)
print(array_2x2[0, 1])
print(array_2x2[:, 0])
print(array_2x2[1])

array 2D: [[1 2]
 [3 4]]
2
[1 3]
[3 4]


In [53]:
print(array_4d, array_4d.shape)
print(array_4d[0])
print(array_4d[0, 0])
print(array_4d[1, :, 1, :])
print(array_4d[:, :, :, 0])

[[[[ 1  2  1]
   [ 3  4  3]]

  [[ 5  6  5]
   [ 7  8  7]]]


 [[[12 13 12]
   [11 12 11]]

  [[13 14 13]
   [15 16 15]]]] (2, 2, 2, 3)
[[[1 2 1]
  [3 4 3]]

 [[5 6 5]
  [7 8 7]]]
[[1 2 1]
 [3 4 3]]
[[11 12 11]
 [15 16 15]]
[[[ 1  3]
  [ 5  7]]

 [[12 11]
  [13 15]]]
